doc: layout-config-reference: Document supported file types
phytec/partup pull request #22
Opened 2023-01-20 12:44 UTC by landerweit-phytec

Document behavior for different file types.

Signed-off-by: Leonard Anderweit <l.anderweit@phytec.de>

2023-01-25 09:16 UTC, mschwan-phytec requested changes

2023-01-25 09:44 UTC, landerweit-phytec commented on doc/layout-config-reference.rst
> +``tar`` archives and ``tar.gz`` compressed archives are extracted into the
Fixed with `tar.*` to include all compressed archives.

2023-01-25 09:45 UTC, landerweit-phytec commented on doc/layout-config-reference.rst
> +overrides the existing filesystem. Additionally ext4 filesystems are resized to
Noted this detail.

2023-01-31 10:30 UTC, mschwan-phytec requested changes

2023-01-31 10:30 UTC, mschwan-phytec commented on doc/layout-config-reference.rst
> +   the existing filesystem, so the filesystem should be specified as
```diff
-the existing filesystem
+any existing filesystem
```
```diff
-, so the filesystem
+, so it
```

2023-01-31 10:30 UTC, mschwan-phytec commented on doc/layout-config-reference.rst
> +   ``filesystem: null`` or not be specified at all. Additionally ext4
s/ext4/ext/g

So it does not sound like only ext4 filesystems are resized afterwards.

2023-01-31 11:03 UTC, landerweit-phytec commented
Thanks for the suggestions. Updated the commit accordingly.

2023-01-31 12:02 UTC, mschwan-phytec approved these changes

2023-01-31 12:02 UTC, merged