Test partup with loop device in github action
phytec/partup pull request #34
Opened 2023-02-15 15:08 UTC by landerweit-phytec

Test partup by writing to loop device instead of physical device. This is a blackbox test as it tests partup as a whole.
The only change to partup itself is support for loop devices in `pu_device_get_partition_path()`.

2023-02-15 15:14 UTC, landerweit-phytec commented
The new test currently fails as result of a bug fixed in #32, but still present here.

2023-07-12 07:51 UTC, mschwan-phytec requested changes

2023-07-12 07:51 UTC, mschwan-phytec commented on .github/workflows/blackox-test.yml
> +          meson compile -C build
You could additionally install partup here, so executing is easier later on:
```
meson install -C build
```

2023-07-12 07:51 UTC, mschwan-phytec commented on tests/config/blackbox/msdos.yaml
> +    filesystem: null
Maybe additionally test `block-size` here?

2023-07-12 07:51 UTC, mschwan-phytec commented on .github/workflows/blackox-test.yml
> +          dd if=/dev/zero of=partup_file bs=1M count=100
Please rename `partup_file` to `loop-file`. I think that better represents its use.

2023-07-12 07:51 UTC, mschwan-phytec commented on .github/workflows/blackox-test.yml
> +            rm tests/data/layout.yaml pkg.partup
How about using `git clean -xdf` to clean files?

2023-07-12 07:51 UTC, mschwan-phytec commented on .github/workflows/blackox-test.yml
Maybe rename "blackbox test" to "system tests", which more precisely describes the testing level, at least according to https://en.wikipedia.org/wiki/Software_testing.

2023-07-12 07:51 UTC, mschwan-phytec commented on .github/workflows/blackox-test.yml
> +name: build
Rename to `system tests` then.

2023-07-12 07:51 UTC, mschwan-phytec commented on tests/data/lorem.tar.gz
Could you briefly describe what you changed in this archive in the commit message? It is not visible while reading the commit history and diff.

2023-07-12 08:35 UTC, landerweit-phytec commented on tests/data/lorem.tar.gz
I removed `lorem.tar.gz` as it is not really need since we have `lorem.tar` now.

2023-07-12 08:37 UTC, mschwan-phytec commented on tests/config/blackbox/msdos.yaml
> +    filesystem: null
Okay, nice!

2023-07-12 08:38 UTC, mschwan-phytec commented on tests/data/lorem.tar.gz
Seems right. :+1:

2023-07-12 13:00 UTC, mschwan-phytec requested changes

2023-07-12 13:00 UTC, mschwan-phytec commented on .github/workflows/system-tests.yml
> +            lorem.txt lorem.tar root.ext4
Please add some indentation here, as the line continues.

2023-07-13 07:22 UTC, mschwan-phytec approved these changes

2023-07-13 07:23 UTC, merged