src: emmc: Add configurable size alignment for expanding partitions
phytec/partup pull request #5
Opened 2022-11-29 14:54 UTC by landerweit-phytec

Add size alignment for expanding partitions. The alignment can be
configured with for each partition individually with 'align'. The
default alignment is 1KiB.

2022-11-30 13:31 UTC, mschwan-phytec requested changes
I am unsure if we should rather rename the option to "block-size" instead of "align". Looking at the man pages of e.g. mkfs.ext4 shows that *alignment* means the positioning of a partition to certain blocks of sectors/bytes. In contrast, *block size* means a multiplication factor the partition size has to fit in, but with no limits to the start and end alignment.

2022-11-30 13:31 UTC, mschwan-phytec commented on doc/layout-config.rst
> +   Aligns the size of the partition to the specified value. The default is 1KiB.
I think we should be more precise regarding the default. It is actually two sectors, which in almost all cases is 1KiB (2 × 512B), but I still think we should mention it that way.

2022-11-30 13:31 UTC, mschwan-phytec commented on src/emmc.c
> +        g_debug("%s: type=%d filesystem=%s start=%lld size=%lld offset=%lld align=%lld expand=%s",
I think it is time to break this string into two lines. The soft limit of 80 characters has been stretched enough. :)

2022-11-30 13:31 UTC, mschwan-phytec commented on src/emmc.c
> +        g_debug("Parsed partition: label=%s filesystem=%s type=%s size=%lld offset=%lld align=%lld expand=%s",
Same for this one. Breaking this string up into two lines would most certainly benefit its readability.

2022-11-30 14:30 UTC, landerweit-phytec commented
Renamed the configuration option from 'align' to 'block-size'.

2022-12-01 15:04 UTC, mschwan-phytec requested changes

2022-12-01 15:04 UTC, mschwan-phytec commented on src/emmc.c
> +                block-size=%lld expand=%s",
Multiline strings should be split like the following:
```
"one "
"two"
```
Using `\` will carry the indentation of the next line into the string, which we do not want.

2022-12-01 15:04 UTC, mschwan-phytec commented on doc/layout-config.rst
> +   default is 2 sectors, which is equal to 1KiB.
Please use the following term here:
```
[...], which is almost always equal to 1KiB.
```

2022-12-02 09:15 UTC, mschwan-phytec approved these changes

2022-12-02 09:15 UTC, merged