Test all mount related functions
phytec/partup pull request #53
Opened 2023-06-15 14:22 UTC by landerweit-phytec

All new tests need to be run as root.

2023-06-19 13:30 UTC, mschwan-phytec commented
The unit test sporadically fails:
```
1/1 partup:root / mount RUNNING
>>> MALLOC_PERTURB_=88 G_TEST_SRCDIR=/home/schwan/documents/github/phytec/partup/tests G_DEBUG_MESSAGES=all G_TEST_BUILDDIR=/home/schwan/documents/github/phytec/partup/build/tests /home/schwan/documents/github/phytec/partup/build/tests/mount
――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ――――――――――――――――――――――――――――――――――――――――――――――――――
TAP version 13
# random seed: R02S6b91ac199a1ba2231876f89fcc1dc5a7
1..6
# Start of mount tests
ok 1 /mount/create_mount_point
ok 2 /mount/mount
ok 3 /mount/umount
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
ok 4 /mount/device_mounted_false
**
ERROR:../tests/mount.c:110:test_device_mounted_true: 'pu_umount(mount_point, &fixture->error)' should be TRUE
not ok /mount/device_mounted_true - ERROR:../tests/mount.c:110:test_device_mounted_true: 'pu_umount(mount_point, &fixture->error)' should be TRUE
Bail out!
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
1/1 partup:root / mount FAIL            0.32s   killed by signal 6 SIGABRT
```
Also, `tests/data/root.ext4` gets modified after running the unit tests. This should be prevented. Maybe the change comes through the mount/umount operation? Looking at the hexdump of `tests/data/root.ext4` before and after running the tests did not reveal any obvious things, though. :thinking:

2023-06-20 09:03 UTC, mschwan-phytec requested changes
Some styling issues...

2023-06-20 09:03 UTC, mschwan-phytec commented on tests/mount.c
> +    g_assert_true(g_spawn_command_line_sync(cmd, NULL, NULL,
Check line wrapping.

2023-06-20 09:03 UTC, mschwan-phytec commented on tests/mount.c
> +    g_assert_true(g_spawn_command_line_sync(cmd, NULL, NULL,
Check line wrapping.

2023-06-20 09:03 UTC, mschwan-phytec commented on tests/mount.c
> +    gint wait_status;
Please separate declaration and initialization of variables. See also other instances.

2023-06-21 08:13 UTC, landerweit-phytec commented
> The unit test sporadically fails:
> 
> ```
> 1/1 partup:root / mount RUNNING
> >>> MALLOC_PERTURB_=88 G_TEST_SRCDIR=/home/schwan/documents/github/phytec/partup/tests G_DEBUG_MESSAGES=all G_TEST_BUILDDIR=/home/schwan/documents/github/phytec/partup/build/tests /home/schwan/documents/github/phytec/partup/build/tests/mount
> ――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ――――――――――――――――――――――――――――――――――――――――――――――――――
> TAP version 13
> # random seed: R02S6b91ac199a1ba2231876f89fcc1dc5a7
> 1..6
> # Start of mount tests
> ok 1 /mount/create_mount_point
> ok 2 /mount/mount
> ok 3 /mount/umount
> # GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
> ok 4 /mount/device_mounted_false
> **
> ERROR:../tests/mount.c:110:test_device_mounted_true: 'pu_umount(mount_point, &fixture->error)' should be TRUE
> not ok /mount/device_mounted_true - ERROR:../tests/mount.c:110:test_device_mounted_true: 'pu_umount(mount_point, &fixture->error)' should be TRUE
> Bail out!
> ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
> 1/1 partup:root / mount FAIL            0.32s   killed by signal 6 SIGABRT
> ```
I assume that mounting and immediately unmounting is a timing problem here. I'll try waiting for the mount operation to be finished.
> 
> Also, `tests/data/root.ext4` gets modified after running the unit tests. This should be prevented. Maybe the change comes through the mount/umount operation? Looking at the hexdump of `tests/data/root.ext4` before and after running the tests did not reveal any obvious things, though. thinking
I'll switch to using a copy of `root.ext` although I don't think this has anything to do with the failing tests.

2023-07-04 14:40 UTC, landerweit-phytec commented
A copy of `data/root.ext4` is now used to not alter the original file.

2023-07-05 08:03 UTC, mschwan-phytec requested changes

2023-07-05 08:03 UTC, mschwan-phytec commented on tests/helper.h
> +                        gconstpointer user_data);
How about keeping this consistent with the other fixtures and rename it to `copy_file_*` and `CopyFileFixture`?

2023-07-05 08:07 UTC, mschwan-phytec commented
> A copy of `data/root.ext4` is now used to not alter the original file.

Somehow the test still modifies the original file for me. :thinking:

2023-07-06 08:15 UTC, mschwan-phytec approved these changes

2023-07-06 08:16 UTC, merged