src: command: Allow passing command usage
phytec/partup pull request #65
Opened 2023-08-17 11:48 UTC by mschwan-phytec

Allow passing a command usage overview by using the special option entry `G_OPTION_REMAINING` and its argument description field.

2023-08-17 14:57 UTC, landerweit-phytec commented on src/pu-command.c
> +                arg_remaining, NULL, "COMMAND" },
If `arg_remaining` is `NULL`at this point, we get a null pointer dereference when `g_option_context_parse` tries to write to it while parsing.

2023-08-17 14:59 UTC, landerweit-phytec commented on src/pu-command.c
> +    if (*arg_remaining) {
```suggestion
    if (arg_remaining && *arg_remaining) {
```

2023-08-17 15:08 UTC, landerweit-phytec commented on src/pu-command.c
> +    g_return_val_if_fail(arg_remaining == NULL || *arg_remaining == NULL, FALSE);
```suggestion
    g_return_val_if_fail(arg_remaining != NULL && *arg_remaining == NULL, FALSE);
```

2023-08-30 11:11 UTC, landerweit-phytec requested changes
Looks mostly good. Only a few comments.

2023-08-31 13:45 UTC, mschwan-phytec commented on src/pu-command.c
> +    context->args = g_malloc0((context->args_len + 1) * sizeof(gchar *));
`g_malloc0_n` does not seem to be widely used, at least in GLib itself. I do not see a huge benefit in using its additional overflow checking, when we only have a few strings to allocate. So I would prefer to use `g_malloc0` after all.

2023-08-31 13:46 UTC, mschwan-phytec commented on src/pu-command.c
>      return res;
Changed in separate commit.

2023-08-31 13:46 UTC, mschwan-phytec commented on tests/command.c
> +        g_clear_error(&error);
Removed clearing the error.

2023-09-01 07:46 UTC, landerweit-phytec commented on src/pu-command.c
> +    context->args = g_malloc0((context->args_len + 1) * sizeof(gchar *));
Ok, we can leave it as is.

2023-09-01 07:50 UTC, landerweit-phytec approved these changes

2023-09-01 07:50 UTC, merged