Add layout config to specify eMMC boot ack
phytec/partup pull request #76
Opened 2024-01-08 14:51 UTC by landerweit-phytec

The eMMC boot ack is required for the TI am6xx SoCs.

2024-01-17 13:55 UTC, mschwan-phytec requested changes

2024-01-17 13:55 UTC, mschwan-phytec commented on src/pu-utils.c
> +    cmd = g_strdup_printf("mmc bootpart enable %u %u %s", bootpart, boot_ack, device);
`gboolean` is of type `int`, not `unsigned int`:
```suggestion
    cmd = g_strdup_printf("mmc bootpart enable %u %d %s", bootpart, boot_ack, device);
```

2024-01-17 13:55 UTC, mschwan-phytec commented on doc/layout-config-reference.rst
> +   Available since: 1.1.0
You can reference the release.
```suggestion
   Available since: :ref:`release-1.1.0`
```
This link will be available with PR #77.

2024-01-22 08:43 UTC, landerweit-phytec commented on src/pu-utils.c
> +    if (!g_output_stream_close(output_ostream, NULL, error))
This commit is indeed for a different problem and got here by accident. I'll remove it from this PR and look into it later.

2024-01-22 10:13 UTC, mschwan-phytec commented
Looks good now!

One important thing that came to my mind is that we most likely should increment the major version when merging this PR, as we have the rule to do this when changing the config specification. I have another PR in the pipeline that adds a new config option, where I thought the same. :thinking: Otherwise we probably get unexpected error messages of nonexistent options when using e.g. partup 1.0.0 with a config tailored for 1.1.0. With a new major version 2.0.0 this would be guarded right away by the API version check at the beginning.

2024-01-23 08:30 UTC, mschwan-phytec approved these changes

2024-01-23 08:30 UTC, merged